//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterFloorApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerProducts
    {
        public int Id { get; set; }
        public int ProductNameId { get; set; }
        public int PartnerNameId { get; set; }
        public int Countity { get; set; }
        public System.DateTime SaleDate { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
